version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  etl:
    container_name: etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BATCH_SIZE: ${BATCH_SIZE}
      MAX_RETRIES: ${MAX_RETRIES}
    volumes:
      - ./etl/data:/app/data
    depends_on:
      - postgres

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
      - etl

volumes:
  postgres_data:
